config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # post '/signup' => 'users#create', :as => 'user'
  resources :users, only: %i[show new create edit index destroy]
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: %i[new create destroy]
  resources :account_activations, only: [:edit]
  resources :microposts, only: %i[create destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.page(params[:page])
    end

  end

  def help
  end

  def contact
    # get contact_path
    # assert_response :success
    # assert_select "title", "Contact | Ruby on Rails Tutorial Sample App"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>


<% provide :title, 'Help' %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app,
  see the <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em> book</a>
</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
    </h2>
    <%= link_to 'Sign up now!', new_user_path, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>