config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # post '/signup' => 'users#create', :as => 'user'
  resources :users, only: %i[show new create edit index destroy]
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: %i[new create destroy]
  resources :account_activations, only: [:edit]
  resources :microposts, only: %i[create destroy]
end

app/views/shared/_contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Hello <%=name%></h1>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains
      <%= pluralize object.errors.count, 'error' %>.
    </div>
<ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate(@feed_items, window: 2) %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About",'#' %></li>
<li><%= link_to "Contact",contact_path%></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<% if logged_in? %>
<li><%= link_to "Users", users_path %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path, method: :delete %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @micropost %>
  <div class="field">
    <%= f.text_area :content, placeholder: 'Compose new micropost...' %>
  </div>
  <span class="image">
    <%= f.file_field :image %>
  </span>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'view my profile', current_user %></span>
<span><%= pluralize(current_user.microposts.count, 'micropost') %></span>